forEach: BoundedContext
fileName: service.yaml
path: {{name}}/kubernetes
---
apiVersion: v1
kind: Service
metadata:
  name: {{name}}
  labels:
    app: {{name}}
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: {{name}}